services:
  - type: web
    name: tennis-predictions-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn working_dashboard:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5001
